// Perguntas e pontuações são editáveis e independentes do HTML.
const s=(inflamatoria=0,muscular=0,compressao=0,rigidez=0,encurtamento=0,instabilidade=0)=>({inflamatoria,muscular,compressao,rigidez,encurtamento,instabilidade});
const q=(id,theme,question,options)=>({id,theme,question,options:options.map(([id,text,scores])=>({id:`${id}`,text,scores}))});
export const QUESTIONS=[
q('q01','Comportamento da dor','Como você descreveria sua dor com mais frequência?',[['a','Forte, constante e irritada',s(4,0,1,1)],['b','Peso, cansaço ou músculos doloridos',s(0,4,0,1)],['c','Choque, queimação ou pontadas que se espalham',s(1,0,5,0)],['d','Travamento ou dificuldade de se mover',s(1,1,0,5)]]),
q('q02','Duração','Quando ela costuma ficar mais presente?',[['a','Mesmo em repouso ou sem posição confortável',s(4,0,1)],['b','Após um dia corrido ou tenso',s(0,4,0,1)],['c','Depois de sustentar uma posição ou esforço',s(0,1,1,1,0,4)],['d','Principalmente ao me mexer depois de ficar parado',s(1,0,0,4,1)]]),
q('q03','Fatores que agravam','O que tende a piorar seus relatos?',[['a','Movimentos em geral parecem irritar',s(4,1,1)],['b','Estresse, rotina pesada ou tensão',s(0,5)],['c','Inclinar, tossir ou carregar peso',s(0,0,5)],['d','Ficar muito tempo na mesma posição',s(0,1,0,1,0,5)]]),
q('q04','Fatores que aliviam','O que costuma trazer mais alívio percebido?',[['a','Pouca coisa parece aliviar',s(4)],['b','Calor, massagem ou descanso curto',s(0,5)],['c','Mudar uma posição específica',s(1,0,4)],['d','Começar a me movimentar devagar',s(0,1,0,5,1)]]),
q('q05','Rigidez','Ao acordar ou após parar, como seu corpo reage?',[['a','Fica muito travado e demora a soltar',s(2,1,0,5)],['b','Sinto os músculos duros',s(0,5,0,1)],['c','Sinto puxar nas pernas ou quadril',s(0,1,0,1,5)],['d','Não noto esse padrão',s()]]),
q('q06','Mobilidade','Qual movimento parece mais limitado?',[['a','Girar ou olhar para os lados',s(0,1,0,5)],['b','Abaixar ou levantar',s(1,1,1,4,2)],['c','Alcançar os pés',s(0,0,0,1,5)],['d','Nenhum em particular',s()]]),
q('q07','Tensão muscular','Você sente pontos dolorosos ou músculos endurecidos ao toque?',[['a','Frequentemente',s(0,5)],['b','Às vezes',s(0,2)],['c','Raramente',s()]]),
q('q08','Flexibilidade','Como é a sensação ao alongar com cuidado?',[['a','Puxamento forte em músculos ou pernas',s(0,1,0,0,5)],['b','Ajuda temporariamente',s(0,2,0,1,3)],['c','Irrita ou espalha a dor',s(2,0,4)],['d','Não percebo diferença',s()]]),
q('q09','Força e controle','Em relação à sustentação do corpo, você relata:',[['a','Sensação de fraqueza ou falta de firmeza',s(0,0,1,0,0,5)],['b','Cansaço após pouco esforço',s(0,3,0,0,0,4)],['c','Movimentos difíceis de controlar',s(0,0,1,0,0,5)],['d','Nada disso',s()]]),
q('q10','Sintomas irradiados','A dor fica concentrada ou se espalha?',[['a','Fica concentrada',s(1,2,0,1)],['b','Vai para braço ou mão',s(0,0,5)],['c','Vai para glúteo, perna ou pé',s(0,0,5)],['d','Muda de lugar',s(0,4,1)]]),
q('q11','Sensibilidade','Você percebe formigamento ou dormência?',[['a','Frequentemente',s(0,0,5)],['b','Às vezes',s(0,0,3)],['c','Não percebo',s()]]),
q('q12','Posições','Qual situação se aproxima mais da sua experiência?',[['a','É difícil encontrar uma posição confortável',s(4,0,1)],['b','Piora ao ficar sentado ou em pé por muito tempo',s(0,2,0,1,0,4)],['c','Piora em uma posição muito específica',s(1,0,4)],['d','Melhora quando começo a me mexer',s(0,1,0,5)]]),
q('q13','Impacto na rotina','O que mais interfere em sua rotina?',[['a','A intensidade e irritação da dor',s(4)],['b','Tensão ao final do dia',s(0,4)],['c','Medo de um movimento espalhar a dor',s(0,0,4,0,0,2)],['d','Falta de mobilidade ou resistência',s(0,1,0,3,1,4)]]),
q('q14','Recorrência','Como esse padrão costuma evoluir?',[['a','Vai ficando mais intenso em pouco tempo',s(4,0,1)],['b','Aparece em períodos de tensão ou sobrecarga',s(0,5)],['c','Retorna após esforço',s(0,1,0,0,0,5)],['d','Varia conforme a rigidez',s(1,0,0,5)]]),
q('q15','Movimento','Qual frase é mais parecida com seu relato?',[['a','Sinto articulações presas ou travadas',s(1,0,0,5)],['b','Sinto músculos curtos puxando',s(0,1,0,1,5)],['c','Sinto que a coluna não sustenta bem',s(0,0,0,0,0,5)],['d','Sinto dor mais sensível ou irritada',s(4,0,2)]]),
q('q16','Intensidade','Nos dias de piora, o que predomina?',[['a','Dor persistente e forte',s(5)],['b','Peso e tensão muscular',s(0,4)],['c','Queimação, choque ou formigamento',s(1,0,5)],['d','Rigidez que limita o movimento',s(1,0,0,5)]]),
q('q17','Resposta ao esforço','Após atividade física ou tarefas, você percebe:',[['a','Irritação que demora a acalmar',s(4)],['b','Músculos cansados e tensos',s(0,5)],['c','Sintoma irradiado ou sensível',s(0,0,4)],['d','Falta de resistência ou estabilidade',s(0,1,0,0,0,5)]]),
q('q18','Percepção geral','Qual pergunta orientadora mais combina com você?',[['a','A dor parece sempre irritada, forte ou inflamada?',s(5)],['b','Você sente músculos tensos, duros ou doloridos?',s(0,5)],['c','A dor se espalha, aperta ou irradia?',s(0,0,5)],['d','Você apresenta dificuldade para se mover ou sente o corpo rígido?',s(0,0,0,5)],['e','Você sente músculos curtos ou puxando?',s(0,0,0,0,5)],['f','Você sente a coluna fraca, instável ou sem firmeza?',s(0,0,0,0,0,5)]])
];
export const RED_FLAGS=[['rf1','Perda de força importante ou progressiva'],['rf2','Dificuldade súbita para caminhar'],['rf3','Perda de controle urinário ou intestinal'],['rf4','Dormência na região íntima'],['rf5','Dor após acidente ou trauma importante'],['rf6','Febre associada à dor'],['rf7','Perda de peso inexplicada'],['rf8','Dor intensa e progressiva'],['rf9','Histórico relevante que preocupa você'],['rf10','Dor noturna intensa que não muda de posição']].map(([id,text])=>({id,text}));
